import { ArrowRight, Check, Link2, LoaderCircle, TriangleAlert } from 'lucide-react';
import { KeyboardEvent, useState } from 'react';
import { trackEvent } from '../services/analytics';
import { analyzeAssetUrl } from '../services/verifyApi';
import type { AssetListingAnalysis } from '../types/verify.types';

export function AssetSourcePanel({ mode, onMode, onAnalysis }: { mode: 'URL' | 'MANUAL'; onMode: (mode: 'URL' | 'MANUAL') => void; onAnalysis: (analysis: AssetListingAnalysis) => void }) {
  const [url, setUrl] = useState(''); const [state, setState] = useState<'IDLE'|'LOADING'|'SUCCESS'|'PARTIAL'|'ERROR'>('IDLE'); const [message, setMessage] = useState(''); const [analysis, setAnalysis] = useState<AssetListingAnalysis | null>(null);
  async function analyze() { if (!url.trim() || state === 'LOADING') return; setState('LOADING'); setMessage(''); trackEvent('asset_url_submitted'); try { const result = await analyzeAssetUrl(url); const complete = Boolean(result.assetName && result.unityVersion && result.pipelineSupport.length); setAnalysis(result); setState(complete ? 'SUCCESS' : 'PARTIAL'); onAnalysis(result); trackEvent(complete ? 'asset_analysis_success' : 'asset_analysis_partial'); } catch (error) { setState('ERROR'); setMessage(error instanceof Error ? error.message : "We couldn't analyze this listing."); trackEvent('asset_analysis_failed'); } }
  function analyzeOnEnter(event: KeyboardEvent<HTMLInputElement>) { if (event.key === 'Enter') { event.preventDefault(); void analyze(); } }
  return <div className="asset-source"><div className="source-tabs"><button type="button" aria-pressed={mode === 'URL'} className={mode === 'URL' ? 'selected' : ''} onClick={() => onMode('URL')}>Asset Store Link</button><button type="button" aria-pressed={mode === 'MANUAL'} className={mode === 'MANUAL' ? 'selected' : ''} onClick={() => onMode('MANUAL')}>Manual</button></div>{mode === 'URL' && <><div className="url-analyzer"><label htmlFor="asset-url"><Link2 size={17} /> Paste Asset Store Link</label><div><input id="asset-url" type="url" value={url} onChange={(event) => setUrl(event.target.value)} onKeyDown={analyzeOnEnter} placeholder="https://assetstore.unity.com/packages/..." /><button type="button" onClick={() => void analyze()} disabled={!url.trim() || state === 'LOADING'}>{state === 'LOADING' ? <LoaderCircle className="spinner" /> : <ArrowRight />}<span>{state === 'LOADING' ? 'Analyzing…' : 'Analyze Asset'}</span></button></div></div>{state !== 'IDLE' && state !== 'LOADING' && <div className={`analysis-state ${state.toLowerCase()}`} role="status" aria-live="polite">{state === 'SUCCESS' ? <Check /> : <TriangleAlert />}<div><strong>{state === 'SUCCESS' ? 'Asset details found' : state === 'PARTIAL' ? "We found some details, but couldn't detect everything." : "We couldn't analyze this listing."}</strong><p>{state === 'ERROR' ? `${message} You can still enter the details manually.` : 'Review and confirm the editable fields below.'}</p>{analysis?.assetName && <span>{analysis.assetName}{analysis.publisherName ? ` · ${analysis.publisherName}` : ''}</span>}</div></div>}<p className="analysis-disclaimer">Listing details are detected automatically and may be incomplete. Review them before verifying.</p></>}{mode === 'MANUAL' && <p className="manual-note">Enter the asset details manually below. Nothing will be fetched.</p>}</div>;
}
